packageExtensions:
  pg@*:
    dependencies:
      pg-native: '*'
  node-fetch@*:
    dependencies:
      encoding: '*'
  debug@*:
    dependencies:
      supports-color: '*'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

yarnPath: .yarn/releases/yarn-3.2.1.cjs
