packageExtensions:
  cosmiconfig-typescript-loader@*:
    dependencies:
      ts-node: '*'
  debug@*:
    dependencies:
      supports-color: '*'
  fast-json-stringify@*:
    dependencies:
      long: '*'
      uglify-es: '*'
  node-fetch@*:
    dependencies:
      encoding: '*'
  pg@*:
    dependencies:
      pg-native: '*'
  retry-request@*:
    dependencies:
      request: '*'
  ws@*:
    dependencies:
      bufferutil: '*'
      utf-8-validate: '*'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

yarnPath: .yarn/releases/yarn-3.2.3.cjs
