services:
  jayudam-backend:
    build: .
    container_name: jayudam-api
    depends_on:
      - redis
    env_file: .env.local.docker
    image: jayudam-api:latest
    restart: on-failure
    ports:
      - 4002:4002
  redis:
    command: redis-server --loglevel warning --logfile ~/redis
    container_name: jayudam-redis
    image: redis:7-alpine
    ports:
      - 6379
    volumes:
      - 'jayudam:/data'
volumes:
  jayudam:
