/* @name deleteUserInfo */
UPDATE "user"
SET creation_time = NULL,
  update_time = NULL,
  bio = NULL,
  birthyear = NULL,
  birthday = NULL,
  cert_agreement = NULL,
  cherry = 0,
  deactivation_time = NULL,
  email = NULL,
  grade = NULL,
  image_urls = NULL,
  invitation_code = NULL,
  is_verified_birthyear = FALSE,
  is_verified_birthday = FALSE,
  is_verified_email = FALSE,
  is_verified_legal_name = FALSE,
  is_verified_phone_number = FALSE,
  last_attendance = NULL,
  name = NULL,
  nickname = NULL,
  personal_data_storing_year = 1,
  phone_number = NULL,
  sex = NULL,
  sleeping_time = NULL,
  town1_count = 0,
  town1_name = NULL,
  town2_count = 0,
  town2_name = NULL
WHERE id = $1
RETURNING blocking_start_time;