name: Continous Integration

on:
  pull_request:
    branches: [develop]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --tag my-image-name:$(date +%s)
